name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npm run typecheck

      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    environment:
      name: github-pages

      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write # to deploy to Pages
      id-token: write

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
